apiVersion: v1
kind: Namespace 
metadata:
  name: roboshop 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop 
subjects:
- kind: User
  name: ramesh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roboshop-cluster-reader
rules:
- apiGroups: ["v1", "apps/v1", ""] # Remove the unnecessary space in the array
  resources: ["secrets", "nodes", "namespaces", "persistentvolumes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: roboshop-cluster-reader
subjects:
- kind: User
  name: ramesh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: roboshop-cluster-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::474115038571:role/eksctl-eks-spot-cluster-nodegroup--NodeInstanceRole-4RKeIbrOWzlU
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |  
    - userarn: arn:aws:iam::474115038571:user/ramesh
      username: ramesh
      groups:
      - roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-30T12:40:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13342"
  uid: eb782159-6265-4c1f-829c-6a7cb48a9254

